name: Create Release

on:
  workflow_call:
    inputs:
      current-tag:
        description: The tag to build
        required: true
        type: string
      extra_args:
        description: Extra args for go-releaser, for example '--snapshot'
        required: false
        type: string
  workflow_dispatch:
    inputs:
      current-tag:
        description: The tag to build
        required: true
        type: string
      extra_args:
        description: Extra args for go-releaser, for example '--snapshot'
        required: false
        type: string

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.current-tag }}
          fetch-depth: 1
          fetch-tags: true

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_INFRA_USER}}
          password: ${{ secrets.DOCKER_INFRA_TOKEN}}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean ${{ inputs.extra_args }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_CURRENT_TAG: ${{ inputs.current-tag }}
