name: Security Testing

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  SAST:
    name: Perform SAST analysis (golangci-lint)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Generate
        run: go generate ./...

      - name: Run SAST (golangci-lint)
        uses: golangci/golangci-lint-action@v8
        with:
          version: "latest"
          only-new-issues: true
          args: --timeout=10m
          skip-cache: true

  SCA:
    name: Perform SCA analysis (govulncheck)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Generate
        run: go generate ./...

      - name: Run SCA (govulncheck)
        uses: golang/govulncheck-action@v1
        with:
          go-version-file: "go.mod"
          go-package: ./...
          cache: false
