name: Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Install go-junit-report
        run: |
          export GOPATH="$HOME/go/"
          export PATH=$PATH:$GOPATH/bin
          go install github.com/jstemmer/go-junit-report@latest

      - name: Generate
        run: go generate ./...

      - name: Run tests
        run: |
          export GOPATH="$HOME/go/"
          export PATH=$PATH:$GOPATH/bin
          go test -v ./... | go-junit-report -set-exit-code > report.xml

      - name: Summarize Test Results
        if: always()
        uses: test-summary/action@v2
        with:
          paths: report.xml
          show: all
